# Generated by Django 4.2.23 on 2025-06-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('unit', models.CharField(default='unit', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(default='manual input', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['item', 'date'], name='items_price_item_id_2bc786_idx')],
                'unique_together': {('item', 'date', 'unit')},
            },
        ),
    ]
