# Generated by Django 4.2.23 on 2025-06-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_pricesnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricesnapshot',
            new_name='item_price__item_id_38e1fe_idx',
            old_name='items_price_item_id_2bc786_idx',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='itemtag',
            table='item_tag',
        ),
        migrations.AlterModelTable(
            name='pricesnapshot',
            table='item_price_snapshot',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='items_tag',
        ),
    ]
