# Generated by Django 4.2.23 on 2025-06-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_url_alter_shop_table'),
        ('items', '0003_rename_items_price_item_id_2bc786_idx_item_price__item_id_38e1fe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop'),
        ),
    ]
