# Generated by Django 4.2.23 on 2025-06-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_url_alter_shop_table'),
        ('items', '0004_alter_pricesnapshot_shop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricesnapshot',
            unique_together={('item', 'date', 'shop', 'unit')},
        ),
    ]
