# Generated by Django 4.2.23 on 2025-06-15 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_pricesnapshot_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesnapshot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
