# Generated by Django 4.2.23 on 2025-06-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_pricesnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
