# Generated by Django 4.2.23 on 2025-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_pricesnapshot_currency'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items_item',
        ),
        migrations.AlterModelTable(
            name='itemtag',
            table='items_itemtag',
        ),
    ]
