# Generated by Django 4.2.23 on 2025-06-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_table_alter_itemtag_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricesnapshot',
            new_name='items_price_item_id_2bc786_idx',
            old_name='item_price__item_id_38e1fe_idx',
        ),
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
        migrations.AlterModelTable(
            name='itemtag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pricesnapshot',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
