# Generated by Django 4.2.23 on 2025-08-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptscan',
            name='image',
            field=models.ImageField(upload_to='uploaded_receipt_images/'),
        ),
    ]
