"""Type stubs for google.generativeai"""
from typing import Any

def configure(api_key: str) -> None: ...
class GenerativeModel:
    def __init__(self, model_name: str) -> None: ...
    def generate_content(self, prompt: str) -> Any: ...
