# Generated by Django 4.2.23 on 2025-07-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_table'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricesnapshot',
            unique_together={('product', 'date', 'shop', 'unit', 'unit_price', 'currency')},
        ),
    ]
