# Generated by Django 4.2.23 on 2025-07-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pricesnapshot_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricesnapshot',
            unique_together={('product', 'date', 'unit', 'unit_price', 'currency')},
        ),
    ]
