# Generated by Django 4.2.23 on 2025-07-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_pricesnapshot_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_product_id',
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='store_product_id',
            field=models.CharField(blank=True, help_text='Optional store-specific product ID', max_length=255, null=True),
        ),
    ]
