# Generated by Django 4.2.23 on 2025-07-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_table'),
        ('products', '0004_remove_product_store_product_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricesnapshot',
            unique_together={('product', 'date', 'unit', 'unit_price', 'currency', 'shop')},
        ),
    ]
