# Generated by Django 4.2.23 on 2025-06-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_url_alter_shop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table=None,
        ),
    ]
